sudo: false
language: vim
addons:
  apt:
    sources:
      - sourceline: 'ppa:pi-rho/dev'
        key_url: 'http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xCC892FC6779C27D7'
    packages:
      - vim-nox
      - libio-socket-ssl-perl
      - libperl-dev

before_script: |
  git clone --depth=1 https://github.com/junegunn/vader.vim.git

  cat /proc/cpuinfo

  # right now, we need at least v8.0.0654
  git clone --depth=1 https://github.com/vim/vim.git --branch v8.0.0654
  cd vim
  ./configure --enable-perlinterp=yes
  make -j4
  sudo make install
  cd ..
  vim --version

script: |
  vader/run.sh
