sudo: false
language: vim
addons:
  apt:
    sources:
      - sourceline: 'ppa:pi-rho/dev'
        key_url: 'http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xCC892FC6779C27D7'
    packages:
      - vim-nox

before_script: |
  git clone --depth=1 https://github.com/junegunn/vader.vim.git

script: |
  vim -Nu <(cat << VIMRC
  set rtp+=vader.vim
  set rtp+=.
  VIMRC) -c 'Vader! vader/*'
