sudo: true
language: C
addons:
  apt:
    packages:
      - vim-nox
      - libio-socket-ssl-perl
      - libperl-dev

env:
  global:
    - BUILD_GIT_RAW="build/ditch-embedded-libgit2"
  matrix:
    - VIM_VER=""          VIM_PPA="ppa:pi-rho/dev"
    - VIM_VER=""          VIM_PPA="ppa:jonathonf/vim"
    - VIM_VER="v7.4.2273" VIM_PPA=""
    - VIM_VER="v7.4.2204" VIM_PPA=""
    - VIM_VER="v7.4.1304" VIM_PPA=""

matrix:
  allow_failures:
    - env: VIM_VER="v7.4.2204" VIM_PPA=""
    - env: VIM_VER="v7.4.1304" VIM_PPA=""

before_script: |
  git clone --depth=1 https://github.com/junegunn/vader.vim.git

  if [ "x$BUILD_GIT_RAW" != "x" ]; then
    git clone --depth=1 --branch=$BUILD_GIT_RAW https://github.com/rsrchboy/p5-Git-Raw.git
    cpanm --sudo ./p5-Git-Raw
  fi

  if [ "x$VIM_VER" != "x" ]; then
    git clone --depth=1 https://github.com/vim/vim.git --branch $VIM_VER
    cd vim
    ./configure --enable-perlinterp=yes
    make -j4
    sudo make install
    cd ..
  elif [ "x$VIM_PPA" != "x" ] ; then
    sudo apt-add-repository --yes $VIM_PPA
    sudo apt-get -q update
    sudo apt-get -y install vim-nox
  else
    echo "Using stock vim!"
  fi

  perl -V

  vim --version

script: |
  vader/run.sh
